# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - coverage/**
    - "**/*.g.dart"
    - "**/*.mocks.dart"
  plugins:
    - dart_code_linter
    - custom_lint

dart_code_linter:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    lines-of-executable-code: 50
  metrics-exclude:
    - test/**
    - build/**
    - android/**
    - coverage/**
    - "**/*.g.dart"
    - "**/*.mocks.dart"
  rules:
    - avoid-dynamic
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - no-empty-block
    - prefer-trailing-comma

custom_lint:
  enable_all_lint_rules: false
  rules:
    - avoid_read_inside_build
    - avoid_watch_outside_build

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true
